sudo: required

# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.0 version
  - 7.0
  # aliased to a recent 7.1 version
  - 7.1

addons:
  hosts:
    - reoc.lo

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
#   - DB=pgsql

# optionally set up exclutions and allowed failures in the matrix
# matrix:
#   exclude:
#     - php: hhvm
#       env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
#   allow_failures:
#     - php: 7.0
#     - php: hhvm

# disable the default submodule logic
git:
  submodules: false

install:
  - cd oc/
  - wget http://codeception.com/codecept.phar
  - cd ..

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - pwd
  - sudo cp -f $TRAVIS_BUILD_DIR/build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS openclassifieds2;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: php codecept.phar run acceptance admin/SetUsersPasswordsCept

# script: cat /etc/hosts

# configure notifications (email, IRC, campfire etc)
notifications:
  email: false
