sudo: required
dist: trusty
# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.0 version
  # - 7.0
  # # aliased to a recent 7.1 version
  # - 7.1

addons:
  hosts:
    - reoc.lo

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
#   - DB=pgsql

# optionally set up exclutions and allowed failures in the matrix
# matrix:
#   exclude:
#     - php: hhvm
#       env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
#   allow_failures:
#     - php: 7.0
#     - php: hhvm

# disable the default submodule logic
git:
  submodules: false

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS openclassifieds2;'

install:
  - cd oc/
  - wget http://codeception.com/codecept.phar

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [ $TRAVIS_PHP_VERSION = "5.5.9" ]; then echo "Using PHP 5.4.9"; fi

  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo apt-get install apache2 php5 libapache2-mod-php5

  - sudo sed -i 's/short_open_tag = Off/short_open_tag = On/g' /etc/php5/cli/php.ini
  - sudo sed -i 's/short_open_tag = Off/short_open_tag = On/g' /etc/php5/apache2/php.ini
  - sudo service apache2 restart

  # enable php-fpm
  - sudo apt-get install php5-fpm -y > /dev/null
  - sudo service apache2 restart
  
  - sudo sed -i 's/short_open_tag = Off/short_open_tag = On/g' /etc/php5/fpm/php.ini
  - sudo service apache2 restart

  # install php5-curl
  - sudo apt-get install php5-curl

  # install gettext
  - sudo apt-get install gettext
  - sudo service apache2 restart

  # Install mcrypt
  - sudo apt-get install php5-mcrypt
  # - sudo mv -i /etc/php5/apache2/conf.d/20-mcrypt.ini /etc/php5/mods-available/
  - sudo php5enmod mcrypt
  - sudo service apache2 restart

  # Install GD
  - sudo apt-get install php5-gd
  - sudo service apache2 restart

  # MySQLi extension
  - sudo apt-get install php5-mysql
  - sudo service apache2 restart

  # configure apache virtual hosts
    # $TRAVIS_BUILD_DIR is the cloned repo, it enters the repo after it clones it
  - sudo cp -f $TRAVIS_BUILD_DIR/build/travis-ci-apache /etc/apache2/sites-available/reoc.lo.conf 
  - sudo a2ensite reoc.lo.conf 
  - sudo service apache2 restart
  # - sudo chmod -R 755 $TRAVIS_BUILD_DIR
  - sudo cp -r $TRAVIS_BUILD_DIR /var/www

  # permissions
  - sudo chown -R root:root /var/www
  - sudo chown -R www-data:www-data /var/www/*
  - sudo chmod -R 755 /var/www/*
  # - sudo chmod -R 755 /var/www/yclas-test

# use the $DB env variable to determine the phpunit.xml to use
# script: php codecept.phar run acceptance admin/SetUsersPasswordsCept

script: 
  # - set -e # don't stop on failure
  - curl reoc.lo/install-yclas.php
  - php codecept.phar run acceptance tests/acceptance/InstallCept.php --steps

after_failure:
  - ls /home/travis/build/kotsios5/yclas-test/oc/tests/_output/

# configure notifications (email, IRC, campfire etc)
notifications:
  email: false
